### ISSUE TITLE
Starting Lives and Uses Not Applying Correctly on Pregenerated World

### ISSUE THREAD

**Issue by EvanoriMemoria** [QuantumXenon/origins-randomiser#8] opened 2023-09-08 20:49 UTC
Version 1.19.2 Fabric

I'm having an issue where a world generated _before_ modifying the origins randomiser config does not apply the newly edited config values to players joining for the first time, after their first death they are put into spectator mode, and have no uses of /randomise, it seems like they are defaulting to 0 of both lives and uses. I started up a test server with the modified config applied on first startup, which did correctly apply the appropriate number of lives and uses to players joining for the first time.

Config used:

```
 {
  "general": {
    "randomiseOrigins": true,
    "randomiserMessages": true,
    "dropExtraInventory": true,
    "allowDuplicateOrigins": false
  },
  "command": {
    "randomiseCommand": true,
    "limitCommandUses": true,
    "randomiseCommandUses": 4
  },
  "lives": {
    "enableLives": true,
    "startingLives": 6,
    "livesBetweenRandomises": 1
  },
  "other": {
    "deathRandomisesOrigin": true,
    "sleepRandomisesOrigin": false,
    "sleepsBetweenRandomises": 1
  }
}

```

**Comment by QuantumXenon** [comment] 2023-09-20 19:23
I've done some testing matching as closely as I could your setup and was not able to reproduce this issue. Could you send me the files you are using and/or the logs?

**Comment by EvanoriMemoria** [comment] 2023-09-20 19:49
I suspect, since you were unable to reproduce it tthat the issue is a mod conflict as I am running the Reincarnation Modpack (https://modrinth.com/modpack/aberrant-reincarnation). I don't currently have the time to test if this is still an issue in the pack with a myriad of changes since then (including no longer using the lives mechanic). But I think that it's unlikely to end up being a bug on your end. As pure speculation, I would guess it has to do with Very Many Players, as we had some other player initialization issues with that installed since I made this report. 

Feel free to close this as you see fit.

Thank you for your wonderful work around the origins mod.

**Comment by QuantumXenon** [comment] 2023-09-20 20:24
I'll have a look at that modpack and see if I can reproduce it with that

**Comment by QuantumXenon** [comment] 2023-09-21 14:49
I'm going to close this issue as I don't think it is an issue with Origins Randomiser.

**Closed by QuantumXenon** 2023-09-21 14:49 UTC
Labels: bug
